OrdererOrgs:
  - Name: Orderer
    Domain: gateway.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.gateway.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Org2
    Domain: org2.gateway.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
